# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.twig_extension.instanceof:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension.comment:
        class: AppBundle\Twig\CommentExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension.firstparagraph:
        class: AppBundle\Twig\FirstParagraphExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension.makelink:
        class: AppBundle\Twig\MakeLinkExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension.parsedown:
        class: AppBundle\Twig\ParsedownExtension
        public: false
        tags:
            - { name: twig.extension } 
